version: '3'
services:
  frontend_tls_srv:
    build: ./frontend_tls_srv
    image: 0891860/testcloud_image:frontend_tls_srv
    ports: 
      - "8082:8082"
    depends_on:
      - mongodaemon_service
      - mongodb_service
      - endecrypt_service

  mongodb_service:
    build: ./mongodb_service
    image: 0891860/testcloud_image:mongodb_service
    ports:
      - 27017:27017
    depends_on:
      - mongodaemon_service
      - endecrypt_service

  mongodaemon_service:
    build: ./mongodaemon_service
    image: 0891860/testcloud_image:mongodaemon_service

  endecrypt_service:
    build: ./endecrypt_service
    image: 0891860/testcloud_image:endecrypt_service
